export type {
  User,
  Merchant,
  Address,
  BankAccount,
  Document,
  Contact,
  Role,
  MerchantStatus,
  OnboardingStatus,
  BusinessType,
  DocumentType,
  DocumentStatus,
  ContactType,
} from "@/generated/prisma/client";
